#! /bin/sh
#  This file is part of the IIINSTRUMENT Pipeline
#  Copyright (C) 2002,2003 European Southern Observatory

#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.

#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.

#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# $Author: yjung $
# $Date: 2004/03/15 08:23:07 $
# $Revision: 1.1.1.1 $
# $Name:  $


#   This script is the autoinstaller for the VLT instrument pipeline
#   packages used by the Instrument Pipeline Installation Procedure
#   (IPIP) to ease the pipeline installation for ESO System Engineering
#   staff.


error () {
    echo "Error: $cmd: $1"
    exit 1
}


#
# Main
#

cmd=`basename $0`
usage="Usage: $cmd installation-path"

setup_configure="./configure --prefix=$1 --disable-fitsio"
setup_make="make"

# The destination directory for the installation is mandatory
if test $# != 1; then
    echo "$usage"
    exit 1
fi

# Configure the package
echo "Setting up pipeline package... "
if eval $setup_configure; then
    :
else
    error "Package setup failed! See logfile for details."
fi

# Compile the pipeline
echo "Building pipeline package... "
if eval $setup_make; then
    :
else
    error "Package build failed! See logfile for details."
fi

# Install the pipeline
echo "Installing pipeline package... "
if eval $setup_make install install-html; then
    :
else
    error "Package installation failed! See logfile for details."
fi

exit 0
